### ISSUE TITLE
Hola, hay un error

### ISSUE THREAD

**Issue by JoseAdrianRodriguezGonzalez** [ibarram/AyE#2]
El código de seno_serie_par.c no es el correcto 
[003_seno_serie_par.c](https://github.com/ibarram/AyE/blob/main/src/003_seno_serie_par.c)
![image](https://github.com/user-attachments/assets/beeb6efc-f461-47fb-b312-c325be733c9f)

**Comment by ibarram** [comment]
El código fue actulizado con la versión correcta
